SmartRouter PROJECT - BETA-2.0 version

diff --git a/base/pkgsrc/root/usr/sbin/changeboot b/base/pkgsrc/root/usr/sbin/changeboot
--- a/base/pkgsrc/root/usr/sbin/changeboot
+++ b/base/pkgsrc/root/usr/sbin/changeboot
@@ -1,121 +1,119 @@
 #!/bin/sh
+# Change boot 1.2 By Washington Rodrigues 2008 
+# Code optimized to SRP by Marcos do Vale 2010
 
-################################################
-# Change boot 1.2 By Washington Rodrigues 2008 #
-################################################
-ARG=`echo "$2" | sed 's/\ *//g'`
+ARG=`echo "$2" | sed 's/[ ]\  *//g'`
 MNT="/var/lib/lrpkg/mnt"
 [ -e "/tmp/boot.info" ] && . /tmp/boot.info
 
 title() {
-  echo
-  echo "Change boot 1.2 "
-  echo "----------------"
-  echo
+ echo
+ echo "Change boot"
+ echo "--------------------------------------------"
+ echo
 }
 
-usage(){
-  title
-  echo "Usage:"
-  echo "changeboot [-boot /dev/xxxx ] or [-boot auto] {-device /dev/xxx}"
-  echo "           [-bootdelay <N> seconds] or [-bootdelay auto] {-device /dev/xxx}"
-  echo "           [-default] {-device /dev/xxx} restore original configuration."
-  echo "           [-info] {-device /dev/xxx} show the actual configuration."
-  echo "           [-showdevice] list all bootable device(s)."
-  echo "           [-repair] {-device /dev/xxx} re-create the config file."
-  echo "           {-device /dev/xxx} override boot.info to force use the other device."
-  echo "           {auto} = original configuration."
-  echo 
-  echo "Example:   changeboot -boot /dev/hda1"
-  echo "           set default boot to hda1"
-  echo
-  exit
+usage() {
+ title
+ echo "Usage:"
+ echo "changeboot [-boot /dev/xxxx ] or [-boot auto] {-device /dev/xxx}"
+ echo "           [-bootdelay <N> seconds] or [-bootdelay auto] {-device /dev/xxx}"
+ echo "           [-default] {-device /dev/xxx} restore original configuration."
+ echo "           [-info] {-device /dev/xxx} show the actual configuration."
+ echo "           [-showdevice] list all bootable device(s)."
+ echo "           [-repair] {-device /dev/xxx} re-create the config file."
+ echo "           {-device /dev/xxx} override boot.info to force use the other device."
+ echo "           {auto} = original configuration."
+ echo 
+ echo "Example:   changeboot -boot /dev/hda1"
+ echo "           set default boot to hda1"
+ echo
+ exit
 }
 
 donesystem() {
-  savesyslinux
-  title
-  echo "Configuration have been modified!"
-  echo "Restart the system to take effect."
-  echo
-  exit
+ savesyslinux
+ title
+ echo "Configuration have been modified!"
+ echo "Restart the system to take effect."
+ echo
+ exit
 }
 
 opensyslinux() {
-   mount -o ro $DEVICE $MNT -t $FSTYPE 2>/dev/null
-   if [ "$?" != 0 ];then
-      title
-      echo "ERROR: Impossible mount device"
-      echo "       check system boot!!!"
-      echo
-      exit
-   fi
-   if [ ! -e "$MNT/syslinux.cfg" ]; then
-      title
-      echo "ERROR: File configuration not found!"
-      echo
-      echo "Use changeboot -repair"
-      echo
-      exit
-   fi
-   SYSLINUX=`cat $MNT/syslinux.cfg`
-   umount $MNT 2>/dev/null
+ mount -o ro $DEVICE $MNT -t $FSTYPE 2>/dev/null
+ if [ "$?" != 0 ]; then
+	title
+	echo "ERROR: Impossible mount device"
+	echo "       check system boot!!!"
+	echo
+	exit
+ fi
+ if [ ! -e "$MNT/syslinux.cfg" ]; then
+	title
+	echo "ERROR: File configuration not found!"
+	echo
+	echo "Use changeboot -repair"
+	echo
+	exit
+ fi
+ SYSLINUX=`cat $MNT/syslinux.cfg`
+ umount $MNT 2>/dev/null
+ echo $SYSLINUX | tr ' ' '\n' > /tmp/changeboot.tmp
+ VARBOOT=`grep -i "^boot=" /tmp/changeboot.tmp`
+ VARDELAY=`grep -i "^bootdelay=" /tmp/changeboot.tmp`
+ rm -f /tmp/changeboot.tmp 2>/dev/null
 }
 
 savesyslinux() {
-   mount -o rw $DEVICE $MNT -t $FSTYPE 2>/dev/null
-   echo -en "$SYSLINUX" > $MNT/syslinux.cfg
-   umount $MNT 2>/dev/null
+ mount -o rw $DEVICE $MNT -t $FSTYPE 2>/dev/null
+ echo -en "$SYSLINUX" > $MNT/syslinux.cfg
+ umount $MNT 2>/dev/null
 }
 
 detectboot() {
-cat /proc/partitions | while read x x LENGHT DEVICE; do
-DETECT=0
-    case $DEVICE in
-         hd??) 
-            TMPDEV=`echo $DEVICE | sed s/[0123456789]//g`
-            if [ "$(cat /proc/ide/$TMPDEV/media)" = "disk" ]; then
-               TYPE="PATA"
-               MODEL=`cat /proc/ide/$TMPDEV/model`
-               DETECT=1 
-            fi;;
-         sd??)
-            INFO=`scsi_info /dev/$DEVICE 2>/dev/null`
-            HOST=`echo $INFO | sed 's/.*HOST=\"//g;s/\".*//g'`
-            MODEL=`echo $INFO | sed 's/.*MODEL=\"//g;s/\".*//g'`
-            ls /proc/scsi/usb*/$HOST 2>/dev/null 1>/dev/null
-            if [ "$?" = 0 ]; then
-               if [ "$(echo $MODEL | grep -c -i "Flash Disk")" = 1 ]; then
-                  TYPE="PENDRIVE"
-               else
-                  TYPE="HDD USB"
-               fi   
-            elif [ "$(echo $MODEL | cut -f1 -d" ")" = "ATA" ]; then
-               TYPE="SATA"
-            else
-               TYPE="SCSI"
-            fi
-            DETECT=1;;
-    esac
-
-if [ "$DETECT" = 1 ]; then
-   INFO=`fdisk -l 2>/dev/null | grep "/dev/$DEVICE" | grep -c -i "\*"`
-   [ "$INFO" = 1 ] && echo "$DEVICE#$TYPE#$MODEL"
-fi
-done     
+ while read major minor blocks name; do
+	DETECT=0
+	case $name in
+	 hd??) 
+		TMPDEV=`echo $name | sed 's/[0123456789]//g'`
+		if [ "$(cat /proc/ide/$TMPDEV/media)" = "disk" ]; then
+		 TYPE="PATA"
+		 MODEL=`cat /proc/ide/$TMPDEV/model`
+		 DETECT=1 
+		fi;;
+	 sd??)
+		INFO=`scsi_info /dev/$name 2>/dev/null`
+		HOST=`echo $INFO | sed 's/.*HOST=\"//g;s/\".*//g'`
+		MODEL=`echo $INFO | sed 's/.*MODEL=\"//g;s/\".*//g'`
+		ls /proc/scsi/usb*/$HOST 2>/dev/null 1>/dev/null
+		if [ "$?" = 0 ]; then
+		 [ "$(echo $MODEL | grep -c -i "Flash Disk")" = 1 ] && TYPE="PENDRIVE" || TYPE="HDD USB"
+		elif [ "$(echo $MODEL | cut -f1 -d" ")" = "ATA" ]; then
+		 TYPE="SATA"
+		else
+		 TYPE="SCSI"
+		fi
+		DETECT=1;;
+	esac
+	if [ "$DETECT" = 1 ]; then
+	 INFO=`fdisk -l 2>/dev/null | grep "/dev/$name" | grep -c -i "\*"`
+	 [ "$INFO" = 1 ] && echo "$name#$TYPE#$MODEL"
+	fi
+ done < /proc/partitions
 }
 
 llign() {
-  lenght=${#1}
-  if [ "$lenght" = "$2" ]; then
-     echo "$1"
-     exit 0
-  fi
-  var=""
-  for POS in $(seq $((lenght+1)) $2); do
-      var=$var"\\040"
-  done
-  echo $1$var
+ lenght=${#1}
+ if [ "$lenght" = "$2" ]; then
+	echo "$1"
+	exit 0
+ fi
+ var=""
+ for POS in $(seq $((lenght+1)) $2); do
+	var=$var"\\040"
+ done
+ echo $1$var
 }
 
 if [ "$3" = "-device" -o "$2" = "-device" ]; then
@@ -143,117 +141,75 @@ if [ "$ISMOUNTED" = 1 ]; then
    echo "ERROR: Please unmount device /mnt to continue!"
    echo
    exit
-fi
-
-if [ "${#2}" -gt 0 ]; then
-   if [ "$1" = "-bootdelay" -a "$ARG" != "auto" ]; then
-      ISNUMERIC=`echo $ARG | sed s/[0123456789]//g`
-      if [ -n "$ISNUMERIC" ]; then
-         title
-         echo "ERROR: Invalid argument, use only numbers!"
-         echo
-         exit
-      fi
-   fi
-fi   
+fi  
 
 case $1 in
-	 "-default")
-                   opensyslinux
-                   echo -en $(echo -e "$SYSLINUX" | sed s/\ */\\\\012/g) > /tmp/changeboot.tmp
-                   VARBOOT=`cat /tmp/changeboot.tmp | grep -i "^boot="`
-                   VARDELAY=`cat /tmp/changeboot.tmp | grep -i "^bootdelay="`
-                   rm -f /tmp/changeboot.tmp 2>/dev/null
-                   [ -n "$VARBOOT" ] && SYSLINUX=`echo -en "$SYSLINUX" | sed s\~" $VARBOOT"~~g`
-                   [ -n "$VARDELAY" ] && SYSLINUX=`echo -en "$SYSLINUX" | sed s\~" $VARDELAY"~~g`
-                   donesystem
-                   ;;
-	    "-boot")
-                   if [ -n "$ARG" ]; then
-                      if [ "$ARG" != "auto" ]; then
-                         opensyslinux
-                         echo -en $(echo -e "$SYSLINUX" | sed s/\ */\\\\012/g) > /tmp/changeboot.tmp
-                         VARBOOT=`cat /tmp/changeboot.tmp | grep -e "^boot="`
-                         rm -f /tmp/changeboot.tmp 2>/dev/null
-                         [ -n "$VARBOOT" ] && SYSLINUX=`echo -en "$SYSLINUX" | sed s\~" $VARBOOT"~" boot=$ARG"~g` || SYSLINUX=`echo -en "$SYSLINUX boot=$ARG"`
-                         donesystem
-                      else
-                         opensyslinux
-                         echo -en $(echo -e "$SYSLINUX" | sed s/\ */\\\\012/g) > /tmp/changeboot.tmp
-                         VARBOOT=`cat /tmp/changeboot.tmp | grep -i "^boot="`
-                         rm -f /tmp/changeboot.tmp 2>/dev/null
-                         [ -n "$VARBOOT" ] && SYSLINUX=`echo -en "$SYSLINUX" | sed s\~" $VARBOOT"~~g`
-                         if [ -n "$ARG" ]; then
-                            donesystem
-                         else
-                            title
-                            echo "ERROR: Invalid Argument!"
-                            echo
-                            exit
-                         fi
-                      fi
-                   fi   
-                   ;;
-       "-bootdelay")
-                   if [ -n "$ARG" ]; then
-                      if [ "$ARG" != "auto" ]; then
-                         opensyslinux
-                         echo -en $(echo -e "$SYSLINUX" | sed s/\ */\\\\012/g) > /tmp/changeboot.tmp
-                         VARDELAY=`cat /tmp/changeboot.tmp | grep -i "^bootdelay="`
-                         rm -f /tmp/changeboot.tmp 2>/dev/null
-                         [ -n "$VARDELAY" ] && SYSLINUX=`echo -en "$SYSLINUX" | sed s\~" $VARDELAY"~" bootdelay=$ARG"~g` || SYSLINUX=`echo -en "$SYSLINUX bootdelay=$ARG"`
-                         donesystem
-                      else
-                         opensyslinux
-                         echo -en $(echo -e "$SYSLINUX" | sed s/\ */\\\\012/g) > /tmp/changeboot.tmp
-                         VARDELAY=`cat /tmp/changeboot.tmp | grep -i "^bootdelay="`
-                         rm -f /tmp/changeboot.tmp 2>/dev/null
-                         [ -n "$VARDELAY" ] && SYSLINUX=`echo -en "$SYSLINUX" | sed s\~" $VARDELAY"~~g`
-                         if [ -n "$ARG" ]; then
-                            donesystem
-                         else
-                            title
-                            echo "ERROR: Invalid Argument!"
-                            echo
-                            exit
-                         fi   
-                      fi
-                   fi
-                   ;;
-            "-info")
-                   opensyslinux
-                   echo -en $(echo -e "$SYSLINUX" | sed s/\ */\\\\012/g) > /tmp/changeboot.tmp
-                   VARBOOT=`cat /tmp/changeboot.tmp | grep -i "^boot=" | sed s/boot=//g`
-                   VARDELAY=`cat /tmp/changeboot.tmp | grep -i "^bootdelay=" | sed s/bootdelay=//g`
-                   rm -f /tmp/changeboot.tmp 2>/dev/null
-                   [ -n "$VARBOOT" ] && VARBOOT="Boot device $VARBOOT (Custom)" || VARBOOT="Boot device $DEVICE $([ "$MEDIA" = "CUSTOM" ] && echo "(Override boot.info)" || echo "(Automatic)")"
-                   [ -n "$VARDELAY" ] && VARDELAY="Boot delay $VARDELAY second(s) (Custom)" || VARDELAY="Boot delay 15 seconds (Default)"
-                   title
-                   echo "Display information:"
-                   echo " + "$VARBOOT
-                   echo " + "$VARDELAY
-                   echo
-                   exit
-                   ;;
-          "-repair")
-                   SYSLINUX=`echo -en "display SRP.dpy\012timeout 0\012default linux\012append  load_ramdisk=1 initrd=root.tgz initrd_dyn=minix ramdisk_size=4096 root=/dev/ram0"`
-                   donesystem
-                   ;;
-      "-showdevice")  
-                   title
-                   echo "  DEVICE     TYPE               MODEL"
-                   echo
-                   detectboot | sort | while read INFORMATION; do
-                                             DEVICE=`echo $INFORMATION | cut -f1 -d"#"`
-                                             TYPE=`echo $INFORMATION | cut -f2 -d"#"`
-                                             MODEL=`echo $INFORMATION | cut -f3 -d"#"`
-                                             echo -e "$(llign /dev/$DEVICE 10) $(llign $TYPE 10) $MODEL"
-                                       done
-                                       echo
-                                       exit;;
+ "-default")
+	opensyslinux
+	[ -n "$VARBOOT" ] && SYSLINUX=`echo -en "$SYSLINUX" | sed s\~" $VARBOOT"~~g`
+	[ -n "$VARDELAY" ] && SYSLINUX=`echo -en "$SYSLINUX" | sed s\~" $VARDELAY"~~g`
+	donesystem
+ ;;
+ "-boot")
+	if [ -n "$ARG" ]; then
+	 if [ "$ARG" != "auto" ]; then
+		opensyslinux
+		[ -n "$VARBOOT" ] && SYSLINUX=`echo -en "$SYSLINUX" | sed s\~" $VARBOOT"~" boot=$ARG"~g` || SYSLINUX=`echo -en "$SYSLINUX boot=$ARG"`
+		donesystem
+	 else
+		opensyslinux
+		[ -n "$VARBOOT" ] && SYSLINUX=`echo -en "$SYSLINUX" | sed s\~" $VARBOOT"~~g`
+		[ -n "$ARG" ] && donesystem || { title; echo "ERROR: Invalid Argument!"; echo; exit; }
+	 fi
+	fi   
+ ;;
+ "-bootdelay")
+	if [ -n "$ARG" ]; then
+	 if [ "$ARG" != "auto" ]; then
+		ISNUMERIC=`echo $ARG | sed 's/[0123456789]//g'`
+		if [ -n "$ISNUMERIC" ]; then
+		 title
+		 echo "ERROR: Invalid argument, use only numbers!"
+		 echo
+		 exit
+		fi
+		opensyslinux
+		[ -n "$VARDELAY" ] && SYSLINUX=`echo -en "$SYSLINUX" | sed s\~" $VARDELAY"~" bootdelay=$ARG"~g` || SYSLINUX=`echo -en "$SYSLINUX bootdelay=$ARG"`
+		donesystem
+	 else
+		opensyslinux
+		[ -n "$VARDELAY" ] && SYSLINUX=`echo -en "$SYSLINUX" | sed s\~" $VARDELAY"~~g`
+		[ -n "$ARG" ] && donesystem || { title; echo "ERROR: Invalid Argument!"; echo; exit; }   
+	 fi
+	fi
+ ;;
+ "-info")
+	opensyslinux
+	[ -n "$VARBOOT" ] && VARBOOT="Boot device $VARBOOT (Custom)" || VARBOOT="Boot device $DEVICE $([ "$MEDIA" = "CUSTOM" ] && echo "(Override boot.info)" || echo "(Automatic)")"
+	[ -n "$VARDELAY" ] && VARDELAY="Boot delay $VARDELAY second(s) (Custom)" || VARDELAY="Boot delay 15 seconds (Default)"
+	title
+	echo "Display information:"
+	echo " + "$VARBOOT
+	echo " + "$VARDELAY
+	echo
+	exit
+ ;;
+ "-repair")
+	SYSLINUX=`echo -en "display SRP.dpy\012timeout 0\012default linux\012append  load_ramdisk=1 initrd=root.tgz initrd_dyn=minix ramdisk_size=4096 root=/dev/ram0"`
+	donesystem
+ ;;
+ "-showdevice")  
+	title
+	echo "  DEVICE     TYPE               MODEL"
+	echo
+	detectboot | sort | while read INFORMATION; do
+	 DEVICE=`echo $INFORMATION | cut -f1 -d"#"`
+	 TYPE=`echo $INFORMATION | cut -f2 -d"#"`
+	 MODEL=`echo $INFORMATION | cut -f3 -d"#"`
+	 echo -e "$(llign /dev/$DEVICE 10) $(llign $TYPE 10) $MODEL"
+	done
+	echo
+	exit
+ ;;
 esac
 usage
-
-
-
-
diff --git a/base/pkgsrc/root/usr/sbin/install b/base/pkgsrc/root/usr/sbin/install
--- a/base/pkgsrc/root/usr/sbin/install
+++ b/base/pkgsrc/root/usr/sbin/install
@@ -1,5 +1,8 @@
 #!/bin/sh
-#Version 1.2 (26/11/2010) --> naufragoweb
+#Version 2.0 (26/11/2010) --> naufragoweb
+#Cahngelog:
+#Sex 07 Jan 2011 12:32:16 BRST  --> add change disk for second partition (naufragoweb)
+
 
 INSTDIR='/tmp/install'
 SRCDIR_SOURCE="/mnt"
@@ -18,7 +21,7 @@ check_yn() {
 abort() {
    umount $INSTDIR 2&>1 
    rm -rf $INSTDIR
-   umount /mnt 2&>1 
+   umount /mnt 2&>1
    echo
    echo "[0;31mInstalation Aborted. Press [ENTER][0m"
    echo
@@ -154,6 +157,47 @@ showhd() {
    echo
 }
 
+defined_disk() {
+number=0
+detecthds | while read LINE; do
+                        number=$(($number+1))
+                        treatline
+                        showhd
+                  done;
+voltar=1
+while [ "$voltar" = 1 ]; do
+      echo -n "Choose the hard disk you want to install : "
+      read junk
+      numb=0
+      LINE=
+      echo -n > $INSTDIR/line
+      detecthds | while read LINE; do
+                        numb=$((numb+1))
+                        [ "$numb" = "$junk" ] && echo $LINE > $INSTDIR/line
+                        number="$numb"
+                  done;
+      LINE=`cat $INSTDIR/line`
+      [ -n "$LINE" ] && voltar=0
+      treatline
+done;
+echo
+echo "You choose:"
+showhd
+}
+
+disk_default_cache() {
+device_cache="$device"2 
+cyl_first=$((($mbs*1024*1024)/($head*$sect*512)))
+cyl_remaining=$(($cyl-$cyl_first))
+if [ "$(($cyl_remaining*$head*$sect/2048))" -le "5000" ]; then
+   default_mbs_cache=$(($cyl_remaining*$head*$sect/2048))
+   size_cache=$(($cyl_remaining*$head*$sect/2048))
+else
+   default_mbs_cache="5000"
+   size_cache=$(($cyl_remaining*$head*$sect/2048))
+fi
+}
+
 case "$hds" in
    0 )
       echo "There isn't any hard disk installed in this computer"
@@ -169,33 +213,12 @@ case "$hds" in
       showhd
       ;;
    * )
-      number=0
-      detecthds | while read LINE; do
-                        number=$(($number+1))
-                        treatline
-                        showhd
-                  done;
-      voltar=1
-      while [ "$voltar" = 1 ]; do
-            echo -n "Choose the hard disk you want to install the System: "
-            read junk
-            numb=0
-            LINE=
-            echo -n > $INSTDIR/line
-            detecthds | while read LINE; do
-                              numb=$((numb+1))
-                              [ "$numb" = "$junk" ] && echo $LINE > $INSTDIR/line
-                        done;
-            LINE=`cat $INSTDIR/line`
-            [ -n "$LINE" ] && voltar=0
-            treatline
-      done;
-      echo
-      echo "You choose:"
-      showhd
+      echo "[0;34mDefined Disk to install de System[0m"
+      defined_disk
       ;;
 esac
 
+.
 check_yn "Are you sure you want to install the System to this Hard Disk ? (y/n) - "
 [ "$YN" = "N" ] && abort
 
@@ -305,7 +328,7 @@ umount /mnt > /dev/null 2&>1
 
 if [ "$format" = "yes" ]; then
    min_part=$(($head*$sect/2048))
-   echo $iface - $showsize MB
+   echo $iface - $size MB
    echo $model
    sfdisk -g $device
    echo
@@ -341,12 +364,43 @@ if [ "$format" = "yes" ]; then
    [ "$YN" = "Y" ] && use_cache=yes
 
    if [ "$use_cache" = "yes" ]; then
-      cyl_first=$((($mbs*1024*1024)/($head*$sect*512)))
-      cyl_remaining=$(($cyl-$cyl_first))
-      default_mbs_cache=$(($cyl_remaining*$head*$sect/2048))
+      case "$hds" in
+            1 )
+               disk_default_cache
+               ;;
+            * )
+               echo "[0;34mDefined disk for install Second Partition (/partition)[0m"
+               defined_disk
+               device_cache="/dev/$hd"
+               if [ "$device_cache" -eq "$device" ]; then
+                  disk_default_cache
+               else
+                  min_part=$(($head*$sect/2048))
+                  echo "$iface - $size MB"
+                  echo "$model"
+                  sfdisk -g $device_cache
+                  default_mbs_cache="5000"
+                  size_cache="$size"
+               fi
+               echo
+               if [ "$size_cache" -lt "$default_mbs_cache" ]; then
+                  default_mbs_cache="$size_cache"
+               else
+                  echo
+                  echo "[0;31mWARNNING!!![0m"
+                  echo "It is strongly recommended not to exceed the default size for the second"
+                  echo "partition. Sizes larger than recommended may cause serious problems for "
+                  echo "your system. If you want to continue with a larger size, is at your own"
+                  echo "risk."
+               fi   
+               ;;
+      esac        
       while [ "$mbs_cache" = "" ]; do
             echo
-            echo -n "Set the size of partition to create in Megabytes (default=$default_mbs_cache MB) : "
+            echo "default          =$default_mbs_cache MB"
+            echo "maximum allowed  =$size_cache MB"
+            echo
+            echo -n "Set the size of partition to create in Megabytes  : "
             read junk
             [ -z "$junk" ] && mbs_cache=$default_mbs_cache
             [ -n "$junk" ] && mbs_cache=$junk
@@ -357,8 +411,12 @@ if [ "$format" = "yes" ]; then
                  echo "Too little. The smaller partition for this hd is $min_part Megabytes"
                  mbs_cache=
             elif [ "$mbs_cache" -gt $default_mbs_cache ]; then
-                 echo "Too big. The hd has only $default_mbs_cache Megabytes remaining"
-                 mbs_cache=
+                 if [ "$default_mbs_cache" -eq "$(($cyl_remaining*$head*$sect/2048))" ]; then
+                    echo "Too big. The hd has only $default_mbs_cache Megabytes remaining"
+                    mbs_cache=
+                 else
+                    mbs_cache=$junk
+                 fi
             fi
       done;
       echo
@@ -368,7 +426,6 @@ if [ "$format" = "yes" ]; then
       echo
       echo "The filesystem recommended format second partition is ext2 (option recommended)"
       echo
-      defautl_cache_par=
       while [ "$type_cache_par" = "" ]; do
             echo "Options:"
             echo
@@ -414,17 +471,35 @@ if [ "$format" = "yes" ]; then
    cyl=$((($mbs*1024*1024)/($head*$sect*512)))
    command="0,$cyl,b,*"
 
-   [ "$use_cache" = "yes" ] && { cache_par="$device"2; cyl_cache=$((($mbs_cache*1024*1024)/($head*$sect*512))); command="$command\n,$cyl_cache,83,"; }
-   
+   if [ "$use_cache" = "yes" ]; then
+      cache_par="$device_cache"
+      cyl_cache=$((($mbs_cache*1024*1024)/($head*$sect*512))) 
+      if [ "$device_cache" = "$device"2 ]; then
+         command="$command\n,$cyl_cache,83,"
+      else
+         command2="0,$cyl_cache,83,"
+      fi
+   fi
    echo $command
    echo
    echo "[0;33m             ======================================[0m"
    echo "[0;33m              Create partition tables on $device...[0m"
    echo "[0;33m             ======================================[0m"
    echo -e $command | sfdisk -q $device || { echo "Error Partitioning "; abort; }
+   if [ -n "$command2" ]; then
+      echo "Cleaning MBR..."
+      dd if=/bin/clean.mbr of=$device_cache count=1 || { echo "Error Cleaning MBR"; abort; }
+      echo $command2
+      echo
+      echo "[0;33m             ============================================[0m"
+      echo "[0;33m              Create partition tables on $device_cache...[0m"
+      echo "[0;33m             ============================================[0m"
+      echo -e $command2 | sfdisk -q $device_cache || { echo "Error Partitioning "; abort; }
+   fi
+
    echo
    echo "[0;33m         =================================================[0m"
-   echo "[0;33m          Creating FAT32 file system on primary partition[0m "
+   echo "[0;33m          Creating FAT32 file system on primary partition [0m "
    echo "[0;33m         =================================================[0m"
    mkdosfs $boot_par || { echo "Error Creating DOS file system"; abort; }
  
@@ -510,6 +585,20 @@ if [ "$upgrade" = "yes" ]; then
    [ -e $INSTDIR/ssh_keys.tgz ] && cp $INSTDIR/ssh_keys.tgz /mnt
 fi
 sync
+
+check_yn "Mark the boot on syslinux.cfg? - You can find problems (y/n) - "
+if [ "$YN" = "Y" ]; then
+SYSLINUX=`cat /mnt/syslinux.cfg`
+echo "1 sed"
+echo -en $(echo -e "$SYSLINUX" | sed 's/[ ]\ */\\\\012/g') > /tmp/changeboot.tmp
+VARBOOT=`cat /tmp/changeboot.tmp | grep -e "^boot="`
+rm -f /tmp/changeboot.tmp 2>/dev/null
+echo "2 sed"
+[ -n "$VARBOOT" ] && SYSLINUX=`echo -en "$SYSLINUX" | sed 's\~" $VARBOOT"~" boot=$boot_par"~g'` || SYSLINUX=`echo -en "$SYSLINUX boot=$boot_par"`
+echo -en "$SYSLINUX" > /mnt/syslinux.cfg
+fi
+#changeboot -boot $boot_pardisk_default_cache
+[ $device = "/dev/hd*" ] && echo "teste"
 
 umount $INSTDIR 2&>1
 rm -rf $INSTDIR
